language: python
python:
  - "3.8"

install:
  - pip install -q -r requirements.txt

stages:
  - name: test
  # - name: deploy

jobs:
  include:
    - stage: test
      name: Unit Tests
      script:
        - cp env-sample.env .env
        - python manage.py test
